### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by atstay** [chrisjherrera/Group-Project-2#1]
- [ ] Create SQL Database w/ MVPs

- [ ] Sequelize Database

- [ ] button.Onclick- basic app.js stuff

- [ ] Skeleton set up

- [ ] Jo on the FRONT

- [ ] clan in the BACK
